#!/bin/sh
#bg_color=#2f343f
bg_color=#293033
text_color=#f3f4f5
htext_color=#9575cd

rofi -show drun -lines 10 -eh 1 -line-margin 4 -width 50 -opacity "87" -bw 0 -color-window "$bg_color, $bg_color, $bg_color" -color-normal "$bg_color, $text_color, $bg_color, $text_color, $bg_color" -color-active "$bg_color, $htext_color, $bg_color, $htext_color, $bg_color" # -font "System San Francisco Display 16"


#rofi -show drun -fullscreen -lines 5 -eh 1 -line-margin 4 -width 100 -padding 486 -opacity "85" -bw 0 -color-window "$bg_color, $bg_color, $bg_color" -color-normal "$bg_color, $text_color, $bg_color, $text_color, $bg_color" -color-active "$bg_color, $htext_color, $bg_color, $htext_color, $bg_color" # -font "System San Francisco Display 16"
